### PR TITLE
A wild CeleryConfig class appears! (and it lets us configure things)

### PR DESCRIPTION
**Pull request by smuuf**
**_This solves the issue https://github.com/gjedeer/celery-php/issues/41.**_

**There is the new `CeleryConfig` class of which instance can be used to modify _celery-php_'s behaviour.**

First and only and for me most important thing at the moment is the new ability to control whether the messages obtained from the queue should stay in the queue after obtaining them.

I tried _(and I think I succeded)_ to not break any old behaviour with this - by my opinion - pretty substantial addition to the _celery-php_'s configurability.

The `CeleryConfig` instance **is optional** and placed at the end of the `Celery` class's constructor. I think most of the constructor's arguments could be placed inside the  `CeleryConfig` object, but for now I wanted **not to create any backwards incompatibility** since this definitely is not a new major version that could or should dare to do such thing.

_Tests are not provided, since I somehow wasn't able to run even the original ones at all. So please feel free to provide them._

### CODE REVIEW

**Comment by gjedeer** [comment]
I can't review/test/merge the code now but this looks interesting. Thanks for caring about backwards incompatibility.

Strange that you could not run the tests.

**Comment by gjedeer** [comment]
With a little change it's merged to the development version of the code, https://github.com/gjedeer/celery-php/tree/celery4_pr66

Thanks again!

**Comment by smuuf** [comment]
Is there any chance the `celery4_pr66` branch will make it to master any time soon?

**Comment by gjedeer** [comment]
Hey, you have write rights to the repo so if you need it, merge it. @jdufresne seems to be working on a new release but based on the old celery3 code so you may need to rebase his changes to celery4.

**Pull request closed without merging**
