### PR TITLE
Leave AMQPConnection and AMQPChannel open after call to PostTask().

### LINKED ISSUE #57: PECL backend broken; leaves open connections
I recently upgraded celery-php to version 2.1, posting a large number of tasks no longer work very well.

When posting multiple tasks in a loop like:

```
for ($i = 0; $i < 1000; $i++) {
    $c = new Celery('localhost', 'myuser', 'mypass', 'myvhost');
    $c->PostTask('tasks.add', array(2,2), false);
}
```

Connections are left open and eventually PECL AMQPConnection deadlocks waiting for a connection to RabbitMQ.

Before 2.1 celery-php would close the connection after `PostTask`.

I was never able to use the same `Celery` instance to post multiple tasks.

---

Starting with commit: <https://github.com/gjedeer/celery-php/commit/029c3123f4a923f278c9d1e72438b184e0a2785d>

`celery-php` leaves 1 connection open with the following test case:

```
<?php

require 'celery-php/celery.php';

$c = new Celery('localhost', 'myuser', 'mypass', 'myvhost');
$c->PostTask('tasks.add', array(2,2), false);
while (true) {
}
```

This is because a connection is created inside `Celery::__construct()` that never gets closed. The connection used to be closed inside `PECLAMQPConnector::PostToExchange()`, however now a new connection is built for this function.

Further, after upgrading to master (v2.1) **2 connections** are opened that are never closed. One for the broker and one for the backend.

---

I would like to fix this, but need some clarification. What is the intention?

Is the intention that connections are created eagerly on instantiation? If so, what is the purpose of `CeleryAbstract::$isConnected`?

Is the intention that connections are created lazily in `PostTask()`? If so, why are multiple connections created in `Celery::__construct()`?

Is the intention that a single instantiation of the `Celery` object can call `PostTask` multiple times? If so, perhaps it shouldn't disconnect inside `PECLAMQPConnector::PostToExchange()`.

I'd be happy to submit a pull request to fix these open connections if the above can be explained.

### PR DESCRIPTION
**Pull request by jdufresne**
Fixes #57

All feedback on the commit is welcome. Thanks.

### CODE REVIEW

**Comment by gjedeer** [comment]
What's the scenario in which this patch is useful?

The typical flow is:
- create Celery object
- call PostTask() one or multiple times
- destroy Celery object when done (disconnect happens here)

This way number of connect() calls is minimized for these cases when PostTask() is called many times

If you need more queues/channels, you create multiple Celery objects and destroy them when not needed any more. You're not supposed to change connection parameters inside a Celery object after posting.

**Comment by jdufresne** [comment]
The scenario is for the typical flow exactly as you've described. Before this change `PostToExchange()`, via `PostTask()`, would disconnected from RabbitMQ. You can see this on line 52 of the old file.

I'm happy to modify the code to meet a need, could you be more specific about what is missing or wrong?

> destroy Celery object when done (disconnect happens here)

Should probably add a `__destruct()` then. Would you like me to do this?

> You're not supposed to change connection parameters inside a Celery object after posting.

I'm not. Can you please point out where this is happening? Or be more specific about what parts of the change concern you? I'm happy to modify it to meet existing needs I'm not aware of.

**Comment by jdufresne** [comment]
@gjedeer Ping? Have you had another chance to take a look at this and answer my questions above? Thanks.

**Comment by gjedeer** [comment]
I understand why you don't want to disconnect after PostTask, and I agree with the reasoning. 

But I don't get why you're storing the channel in an array. A regular variable is enough. There is no scenario in which a single object will handle more than 1 connection.

**Comment by jdufresne** [comment]
I've reworked the patch based on your suggestion. Let me know if this is what you had in mind. All feedback is welcome.

**Comment by gjedeer** [comment]
Looks good, thanks!

**Comment by jdufresne** [comment]
Thanks!

**Comment by jdeniau** [comment]
Hi, can you publish a new version for this fix ?

Thank you !

**Comment by gjedeer** [comment]
Sorry, I have no time to do it right now.

**Pull request merged**
